name: Latest





on:
  push:
    tags:
      - vl/*





jobs:

  tagging:
    name: Latest
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2





      - name: Docker - Node.js - GPR
        run: |

          VER=$(jq -r '.version' package.json)
          BASE=docker.pkg.github.com/${GITHUB_REPOSITORY}/node

          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

          docker pull ${BASE}:${VER}
          docker tag ${BASE}:${VER} ${BASE}:latest
          docker push ${BASE}:latest





      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: NPM - npmjs
        run: npm dist-tag add $(jq -r '.name + "@" + .version' package.json) latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}





      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com

      - name: NPM - GPR
        run: npm dist-tag add $(jq -r '.name + "@" + .version' package.json) latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
